### ISSUE TITLE
Naga in spitescale cove are broken. Orc/Troll Starer zone

### ISSUE THREAD

**Issue by Ysil69** [ottconnect/Legion#106]
The Naga wavecrashers spawn in their death animation. Making them impossible to attack. They won't aggro you for walking by, but if you try to kill a spiritscale they will aggro you and you can't attack them back.

**Comment by ottconnect** [comment]
need more info regarding your issue at this time, you are basing it as i know all the npc by name lol, can i get a wowhead link to the npc and i'll begin to check in the database at the creature_template.

**Comment by Ysil69** [comment]
http://www.wowhead.com/npc=38300/spitescale-wavethrasher
________________________________

**Comment by ottconnect** [comment]
Issue has been resolved on version 1.0.1.8
