### ISSUE TITLE
Gold cap, legion legendary cap.

### ISSUE THREAD

**Issue by Tyrael75** [ottconnect/Legion#107]
The gold cap in the project is 999,999G which is far from the 9,999,999G of retail. Legion Unique Cap of 1 on legendaries is 1 instead of 2 (could potentially add a means outside dbc editing to increase the max on legendaries mayhaps a configurable option in world config?) Note: There is an upgrade in the order hall upgrade npc that enables 2/2 legendaries which would go back towards incomplete orderhalls, this upgrade is only available at the end of the order hall questline which as far as I could see is not possible without spending time gming quest takes and completions, which i'm not even sure if that interface for order hall upgrades would even be called anyways.

**Comment by ottconnect** [comment]
isssue will be resolved on **version 1.0.1.9**
