### ISSUE TITLE
Visual combat char window bug (maybe client issue)

### ISSUE THREAD

**Issue by LeRutY** [ottconnect/Legion#110]
Sometimes around my own char status window (normally in the top left in ingame ui) stays the red colour. It shows that your char is in combat. But I already killed the enemies and the colour stays. I can see my level. If you are in a fight then you just see 2 crossed weapons (I don´t know exactly what it is). But that´s not the case. After a while the red colour disappears. It can be deadly just to look at the colour when you flee, because you maybe run into other mobs and die.

It could be a unique bug in 7.2.5, I never had that bug.

I upload a screenshot for better understanding what the problem is.

![wowscrnshot_073017_222750](https://user-images.githubusercontent.com/29675883/29119552-e2deb47c-7d06-11e7-93bd-5713eb239f0f.jpg)

**Comment by ottconnect** [comment]
this should be fixed on the next update, if its not please reopen the issue if 1.0.2.0 doesn't work.

**Comment by LeRutY** [comment]
It wasn´t fixed but there are enough more important things broken.
