### ISSUE TITLE
Pandarian starter area

### ISSUE THREAD

**Issue by vproph3t** [ottconnect/Legion#115]
Pandarian starter area causes a server crash it may take 5 to 10 mins before the server crashes out. Basically it will freeze your pc.

**Comment by ottconnect** [comment]
i've tested this out and don't seem to have an issue with loading pandaren on a windows 10 pro 3gb of ram only lol for my test laptop

**Comment by vproph3t** [comment]
it is the Wandering Isle part mine crashed up while questing, my partner crashed the server while she was there as well. That's what made me go and check it out in the first place..
I am running windows 10 home edition 8gb of ram and l run it as a server for home use.

I have done some basic fixes ie lootid and repaired 4 quests that crash the server. Which l can send you the sql's if you want them they are only on the human side at the moment.

**Comment by ottconnect** [comment]
for the pandaren zone i've got the basic already created on post
https://github.com/ottconnect/Legion/issues/20

52 quest are completed out of 80 but i know their about 90 quest in the start zone

**Comment by vproph3t** [comment]
The four quests that crashed the server when you hand then in are..

Back in Yak - 30492
Make A Fighter Out of Me - 30942
The Pools of Youth - 30347
Threat from Dojan - 30349

l have fixed them if you need the sql's let me know  :)

Once again thank you ottconnect

**Comment by ottconnect** [comment]
add me on skype and we can exchange ideals.

Skype: ottconnect

**Comment by ottconnect** [comment]
but what i have notice is that the quest mentioned are not listed on gamepedia wow

**Comment by ottconnect** [comment]
those are all higher level quest but you can send them to me on skype
