### ISSUE TITLE
Watching out back' Quest - Blasted Lands

### ISSUE THREAD

**Issue by buenodart** [ottconnect/Legion#134]
You have to examine the Horde Plans in a papper. But you can't use the papper. Doens't work

**Comment by LeRutY** [comment]
Both http://www.wowhead.com/quest=25695/watching-our-back and http://www.wowhead.com/quest=26174/watching-our-back

You can click on them but there isn´t that little window showing up, so you can´t take the plans.

**Comment by ottconnect** [comment]
already reported
