### ISSUE TITLE
Priest's Immortal Specialization Fix

### ISSUE THREAD

**Issue by buenodart** [ottconnect/Legion#138]
@ottconnect Hey brow!

I dont know if i posted this solution before... so... here it is:

https://github.com/TrinityCore/TrinityCore/commit/9d29c002ef16ed3c7d6aa3978184b8909f6a9c4a

https://github.com/TrinityCore/TrinityCore/commit/a834c66a4e637edfc1d271daf3c64468fb8c731f

Thanks bro

**Comment by LeRutY** [comment]
Lol yes, you already did https://github.com/ottconnect/Legion/issues/116

**Comment by buenodart** [comment]
Oh! Right! Sorry ^^

**Comment by ottconnect** [comment]
already resolved
