### ISSUE TITLE
Zepplin in tirisfal glades sticks players.

### ISSUE THREAD

**Issue by TitoDM** [ottconnect/Legion#169]
Not every time but most the time, a player going from tirisfal to org will be stuck in the airship in the middle of the water the airship then goes on an infinite loop.

**Comment by pisette911** [comment]
I was able to resolve that by using the provided map extractors to compile the Mmaps folder, then edit the worldserver.conf to enable them. That issue was also happening for boats

**Comment by XCobra** [comment]
This isn't a simple to solve core issue, and has been around forever. mmaps While "optional" to run the server really should be considered a requirement, they're easy to put in and keep things like this from happening.
