### ISSUE TITLE
World Vendor Issues (Can't buy items from vendor)

### ISSUE THREAD

**Issue by Ragefart** [ottconnect/Legion#21]
- [x] Buying stuff from Vendor does not work (any vendor)
- [x] Selling stuff to vendor works
- [x] Rebuying stuff works aswell
- [x] Opcodes
- [x] Packets

**Comment by ottconnect** [comment]
I'll be doing some searching with the packets and opcodes.

**Comment by ottconnect** [comment]
Just a question regarding this are you able to buy bank slots ?

**Comment by ottconnect** [comment]
Issue has been resolved on Core 1.0.0.5 and database 1.0.0.5
