### ISSUE TITLE
Link for 6.1.2?

### ISSUE THREAD

**Issue by IS4Code** [ottconnect/Legion#217]
Where can I download the repack for 6.1.2? All links point to the website, but I cannot find the download links anywhere.

**Comment by ottconnect** [comment]
This is the legion project not wod and we have merged all the work from the other repack to the legion repack

**Comment by IS4Code** [comment]
Well, this is the "forum", so I am asking here. I wasn't able to find the download link, and I am looking for this specific version. Are there no download links for it?

**Comment by LeRutY** [comment]
That´s a very specific version, so I guess no.

**Comment by IS4Code** [comment]
Well, I suppose any 6.1 would be sufficient, if I also find the client.
