### ISSUE TITLE
connection_patcher fails on both wow and wow-64 binaries

### ISSUE THREAD

**Issue by Xlaits** [ottconnect/Legion#226]
Dragging the binaries onto the connection_patcher, I get the following error, and can not continue.

Creating patched binary...
Determined build number: 25383
Win32 client...
patching Portal
Found offset 14980348
patching redirect RSA Modulus
Found offset 14482864
patching BNet certificate file location
Found offset 14945508
patching BNet certificate file to load from local path instead of CASC
EX: unable to find pattern
An error occurred. Press ENTER to continue...

Or this from wow 64
Creating patched binary...
Determined build number: 25383
Win64 client...
patching Portal
Found offset 21356736
patching redirect RSA Modulus
Found offset 20782640
patching BNet certificate file location
Found offset 21315488
patching BNet certificate file to load from local path instead of CASC
EX: unable to find pattern
An error occurred. Press ENTER to continue...

**Comment by Eredar** [comment]
You posted it without reading?
Determined build number: 25383

It's 7.3.2 Live build. His core for 7.2.5.24461 (or maybe other 7.2.5 builds).

**Comment by Xlaits** [comment]
@Eredar I only realized it AFTER I posted it. And it does work up to 247xx or whatever that number is. I've had to use MortalWOW's mini-launcher, which does not work by itself...

**Comment by Zelot128** [comment]
May i ask how you got mortalWOWs launcher to work?
