### ISSUE TITLE
Worgen Starter Town Issues

### ISSUE THREAD

**Issue by Xlaits** [ottconnect/Legion#227]
I noticed a few things when starting a new character as a Worgen on a completely empty server.

1. I did notice that there are a RIDICULOUS amount of spawns in the main Worgen town, so much so that it is almost unplayable in it's current state, due to the density of hostile NPCs. The density of the hostiles is so great that one of the quests is completely unobtainable.

2. Some NPCs also move when they are not supposed to, such as one of the injured villagers in the military district. At the same time, some guards are VERY slow to react, or do not react at all.

3. When respawning from death, at the cart, there ARE HOSTILE NPCs VERY close to that respawn location, and can lock a player into a death loop. They're close enough to aggro anyone who's died near or on the cart, and is able to respawn there.

**Comment by Eredar** [comment]
Actually there's almost no sense to post issues, since it looks like ottconnect abandoned his project ~2 months ago and his source is private, so noone will fix this for ya. Better get trinity source, compile it and post issues there.

Btw: 1. Missing npc/go phases 2. Missing flags/auras 3. Maybe same as first one, but more likely simple doublespawns that should be removed.

**Comment by Xlaits** [comment]
@Eredar Even still, I have to try. Personally, I've never actually worked a project from the ground up before, so I'd have no idea where to start, to be quite honest.

**Comment by Eredar** [comment]
It's really simple, just follow the instructions at https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130077/Installation+Guide step by step.

**Comment by Xlaits** [comment]
@Eredar Oh! Thank you. I would have NEVER guessed that I could run this on Linux without that, which means I can allocate even MORE memory to it! I'm going to take a guess and say I'm going to have to extract the maps again, which was a nightmare...

**Comment by Traesh** [comment]
Juste switch to https://github.com/AshamaneProject/AshamaneCore x)

**Comment by LeRutY** [comment]
"It´s really simple" Ah it´s not. "Unable to find the requested boost libraries." Did that what the TrinityCore site says.
