### ISSUE TITLE
Stuck at Logging in to game server screen

### ISSUE THREAD

**Issue by mrk1995** [ottconnect/Legion#24]
![image](https://cloud.githubusercontent.com/assets/29030214/26534557/d120e044-4425-11e7-83af-82e4b46807e8.png)

- [ ] Stuck At log into the same server screen
- [x] not a repack bug connection issue
- [x] Firewall issue
- [x] Core confirmation
- [x] Database confimation
- [x] Repack installed correct
- [x] Client config.wtf setup
- [x] wow_patched.exe
- [x] Able to see realmlist when logging into the game

**Comment by ottconnect** [comment]
What Client verison are you using

**Comment by githubjawill** [comment]
![2017 05 29-1](https://cloud.githubusercontent.com/assets/29031833/26536811/1a9bc0b2-446d-11e7-9f11-9e345deab80c.jpg)
In my case,also take time waiting.
Client version 7.2.0 (24015) X64
Worldserver loaded 100% and gave worldserver.exe permission on the firewall.

**Comment by ottconnect** [comment]
Try and replace this at the top of config.wtf file with this

SET portal "127.0.0.1"
SET textLocale "enUS"
SET audioLocale "enUS"
SET agentUID "wow_enus"

When you get a yellow highlight, means that the bnetserver cannot detect 100% the worldserver, means something is blocking it

**Comment by ottconnect** [comment]
Another question are you hosting it on another computer or on the same computer?

**Comment by githubjawill** [comment]
I don't have SET agentUID "wow_enus" line.
Should i add this line?
And i host it on the same computer.
Thank you.

**Comment by ottconnect** [comment]
add all the lines mentioned

**Comment by mrk1995** [comment]
![is1](https://cloud.githubusercontent.com/assets/29030214/26549734/b44bc93e-447a-11e7-9579-ffd3a79a743e.png)
![is2](https://cloud.githubusercontent.com/assets/29030214/26549736/b44d8b02-447a-11e7-9aec-fa30d4f9a1ea.png)
![is3](https://cloud.githubusercontent.com/assets/29030214/26549735/b44c0c46-447a-11e7-8367-6d1197361c6d.png)

**Comment by mrk1995** [comment]
im hosting from self computer, and use the correct client version

**Comment by ottconnect** [comment]
Then if you have the correct client version and correct database and core, and the config is done correct, then the only possible issue would be the firewall is blocking you access to you worldserver.
You will get a pop up box once the worldserver load to unblock or block from firewall, did you see that pop up box

My suggestion is take all the server files and transfer it in a different folder to trick the firewall of thinking its a new program and once the pop comes up just unblock access to worldserver.exe and bnetserver and mysql again. see if that works out for you

**Comment by mrk1995** [comment]
yep its pop up and enabled them tried to disable firewall but the problem is doesnt solved

**Comment by mrk1995** [comment]
tried with my old wotlk/cata/mop repack and got the same issue :/ hmmm idk what is the problem all worked perfectly at the past years the only thing what is differenc now im update my win7 to win 10

**Comment by ottconnect** [comment]
I have windows 10 Pro 64bits, and i have no issues Logging into the Server, and if your having issues with the other repacks, then it doesn't seem to be a repack issue but your computer is not allowing you to connect, I will continue to scratch my head and come up with something to help you out, but right now this is not a repack bug

**Comment by mrk1995** [comment]
yup its not a repack bug, something blocked my connection to the server but idk what. Never seen this problem before this

**Comment by ottconnect** [comment]
Let me figure it out, I have seen this issue and something is blocking the connection for sure, do you have any other programs open that might be causing this issue ?

Also did you modify the build in the database by chance under auth.realmlist ?

**Comment by mrk1995** [comment]
nope im dont change anything and i think im dont running any other program ehat can block my connection, disabled every torrent/blizzard/steam etc. app

**Comment by ottconnect** [comment]
Did you try moving all the server files in a new folder and starting them again ?

**Comment by mrk1995** [comment]
yep tried new folder, new hdd dont solve :/

**Comment by ottconnect** [comment]
Because i did the same thing switch it to another folder and didn't have any issues at all on my end

**Comment by ottconnect** [comment]
I've tested the repack on multiple computer and vps server and I can't reproduce this issue at all, after futher investigation something is blocking your access to the worldserver, if I would be on your computer i would be able to determined more the issue but at this point i cannot do that.

if you can verify what might be blocking the issue and you do find a resolution please let me know.
I will keep my eye on other forum and website that come accross this issue and I will leave this issue opened until a fix is applied for your issue

**Comment by graywood** [comment]
Hope you don't mind me chiming in here on your issue, but I ran into a similar issue when I enabled the Auction House Bot and enabled the misc items. This in turn caused an error with the SQL database and I had to delete all the rows in the the auctionhouse data because they didn't have a itemowner. Not saying this is your problem, however you may want to see if you have any database errors in your logs. Once I deleted those rows and updated the database, the problem went away and I could login and play again.

Another thing to mention is this sounds like a permissions issue so try running the bnetserver and worldserver as administrator.

**Comment by ottconnect** [comment]
haven't heard anything or couldn't reproduce this issue in over a month, i suggest updating the client to the correct build and making sure the client build in the database matches the client build.
