### ISSUE TITLE
Can't fish!

### ISSUE THREAD

**Issue by githubjawill** [ottconnect/Legion#26]
![2017 05 29-2](https://cloud.githubusercontent.com/assets/29031833/26537272/889ec188-4470-11e7-8f52-e9955e9bc4f6.jpg)
I can't click the bobber to get the fish.
Thank you.

- [ ] Item_loot_template issue
- [ ] Item number
- [ ] Check wowhead for loot confirmation
- [ ] core confirmation
- [ ] opcodes
- [x] packets
- [x] can't click on bobber
- [x] can throw fishing rod line in the water
- [ ]

**Comment by ottconnect** [comment]
Will review this once i get a chance.

**Comment by ottconnect** [comment]
You wouldnt have the bobber item number

if you get the addon called idtip and it will show you the item number and also spells number etc...

if you don't have it, i'll just have to do research on it so i can check the item_loot table

**Comment by githubjawill** [comment]
![20170530](https://cloud.githubusercontent.com/assets/29031833/26567785/8e30c3c4-4530-11e7-84e2-f2eab5c5209f.jpg)
ID: 131490

**Comment by githubjawill** [comment]
![2017 05 30-2](https://cloud.githubusercontent.com/assets/29031833/26567999/71e7ecfe-4532-11e7-873d-30fee6875aae.jpg)
The three ID are not the same.
I hope it will be helpful to you.

**Comment by ottconnect** [comment]
i know its been over a month since i've updated this but this issue has been resolved for the fishing on the next update.
