### ISSUE TITLE
Already Looted issue

### ISSUE THREAD

**Issue by graywood** [ottconnect/Legion#36]
Quest located at Fargodeep Mine "Gold Tooth" quest item "Bernice's Necklace" Item 981 appears to have a loot flag similar to a flag for a raid or dungeon where you get the message. "Already Looted".
Killed Goldtooth several times and get this message. After quite a few kills it let me loot so there must be a round robin type loot flag. I would assume this is a zone issue because it also affects looting for the quest "Gold Dust Exchange" and "Kobold Candles", which are in the same zone. Fargodeep Mine".

Thanks

- [x] Quest 29424 Items Of Utmost Importance
- [x] Quest 87 Gold Tooth
- [x] Quest 47 Gold Dust Exchange
- [x] Quest 8338 Tainted Arcane Silver
- [x] Quest 26732 Bad Medicine
- [x] Quest 62 The Fargodeep Mine
- [x] Quest 60 Kobold Candles

**Comment by ottconnect** [comment]
Found the issue with Quest number : 29424
Npc: 54130
Item: 72071


Can't loot, error message: Already Looted ( 13710284/  24754052 )

**Comment by ottconnect** [comment]
- [x] Quest 29424 Items Of Utmost Importance
- [x] Quest 87 Gold Tooth
- [x] Quest 47 Gold Dust Exchange
- [x] Quest 8338 Tainted Arcane Silver
- [x] Quest 26732 Bad Medicine
- [x] Quest 62 The Fargodeep Mine
- [x] Quest 60 Kobold Candles

All Quest listed has been fixed.

**Comment by ottconnect** [comment]
Added on core version 1.0.1.5 all already looted issues has been resolved

**Comment by ottconnect** [comment]
This issue was suppose to be resolved on version 1.0.1.5 but an error cause the fix not to be added

So we have added this fix for all the already looted issue to be resolved on 1.0.1.6

Please let me know if the issue continues.
