### ISSUE TITLE
Bounty Board in Elwynn Forrest missing quest: Bounty on Murlocks.

### ISSUE THREAD

**Issue by graywood** [ottconnect/Legion#38]
Bounty on Murlocks: Quest=46 is missing from the Bounty Board next to Guard Thomas.

Thanks

- [x] Quest=46 missing

**Comment by ottconnect** [comment]
Question regarding your quest adventure before coming to this issue, **Deliver the Thomas Report** is the prerequisite to this quest, but it is not listed as such on Wowhead. Did you complete that quest before you went to the board ?


Second if you did complete that quest **Deliver the Thomas Report** 
Get a Database editor, Heidisql if you want.
Login into the database and click on world
then enter the line below into the query tab and boot the server, complete quest **Deliver the Thomas Report** 

Then go to the board and the quest will be available to you.

REPLACE INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `Data24`, `Data25`, `Data26`, `Data27`, `Data28`, `Data29`, `Data30`, `Data31`, `Data32`, `RequiredLevel`, `AIName`, `ScriptName`, `VerifiedBuild`) VALUES (203733, 2, 2491, 'Bounty Board', '', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 19342);

**Comment by ottconnect** [comment]
**Added to Database 1.0.0.7**
