### ISSUE TITLE
DB login

### ISSUE THREAD

**Issue by Humbalomba** [ottconnect/Legion#43]
Howdy, just installed the repack, all works fine no problem in logging into the game and play. but I can't log into the database. I have tried Navicat and heidiSQL nothing works.

The info I'm putting in is:
Username: root
Pass ascent
host: localhost or the ip 
port: 3306

Everything is running, just get an error when trying to connect to db

**Comment by ottconnect** [comment]
3307, i've mentioned this on ac web in a post, and you can also look in the worldserver.conf for the database info.

**Comment by Humbalomba** [comment]
I found it. But Ty.

________________________________
