### ISSUE TITLE
Crash LOG 

### ISSUE THREAD

**Issue by Mbeardmore** [ottconnect/Legion#48]
[GD98KL1_worldserver.exe_[19-6_15-15-51].txt](https://github.com/ottconnect/Legion/files/1085206/GD98KL1_worldserver.exe_.19-6_15-15-51.txt)

Crashed as soon as i loaded up a human monk Here is the crash log

**Comment by ottconnect** [comment]
stop using the 64bit core as we mentioned on ac web and use the 32bit core for now until we resolve the issue with the 64bit core.

**Comment by ottconnect** [comment]
looking threw the crash logs its the same ones as me, we are still looking at this issue and it might just be a memory leak somewhere in the core.

**Comment by ottconnect** [comment]
64 bit test core please provide your crash log if you have an issue

https://drive.google.com/open?id=0ByMbyQDZai7zeEVGNFN2OTFHRlE

**Comment by ottconnect** [comment]
well since i haven't received an answer from this issue, post is closed
