### ISSUE TITLE
My Crash log

### ISSUE THREAD

**Issue by Sfrjoshpro** [ottconnect/Legion#49]
http://jmp.sh/GHJzQt6

Seems to be with modify speed maybe

**Comment by ottconnect** [comment]
64 bit test core, please provide your crash logs here if you have any after downloading and testing this core

https://drive.google.com/open?id=0ByMbyQDZai7zeEVGNFN2OTFHRlE

**Comment by Sfrjoshpro** [comment]
http://jmp.sh/38tx7Gp

**Comment by Sfrjoshpro** [comment]
Gm mod and speed mod no reason  look just like org is the issue  the front gate

**Comment by Sfrjoshpro** [comment]
Also if u could lmk what u found in the logs and where so i can learn and maybe help more.
i know im limited bc im not working with ur SC but lmk

**Comment by Sfrjoshpro** [comment]
http://jmp.sh/3vwrqoP
tele to shatt city

**Comment by ottconnect** [comment]
thanks for the feedback seems like your the only person that understood to post your crash logs, much appreciate, i will review this and you can add me on skype : ottconnect

**Comment by ottconnect** [comment]
see this what i needed, getting the crash logs helps because the teleport issue is another problem that needs to be address, thanks for the feedback

**Comment by Sfrjoshpro** [comment]
Skype invite sent. Look forward to help more

**Comment by ottconnect** [comment]
we have compiled another core right now and are doing further testing to see if the core stabled itself.

Once i get 100% confirmation after testing i will post the core for further testing to the community.

**Comment by ottconnect** [comment]
test core and let me know if it crashes

https://drive.google.com/open?id=0ByMbyQDZai7zeWRVRXFrNExsMEU

**Comment by ottconnect** [comment]
issue has been resolved with the updated core, i will update ac web with the updated cores later on today
