### ISSUE TITLE
Horde - Undead - Rogue

### ISSUE THREAD

**Issue by Arantis** [ottconnect/Legion#50]
I don't know if that is known but i can't find an issue for that.

If you start as an Undead - Rogue you can't complete the 3rd Quest (Kill 6 of the Monster) and the server gives out an error that the Quest Reward is not correct. (i can send complete error log if needed).

So you can't complete the Quest and then you won't get a lot quests at all afterwards.

**Comment by ottconnect** [comment]
No i don't need the logs for this i can reproduce the issue and i will address once we get the core up and running at this point i'll put this on hold until we are done with the 64bit core fix.

**Comment by Arantis** [comment]
ok perfect. Is it okay if i open an issue for such issues like this one? I was playing a lot with the repack and found a couple of these issues :)

Anyway GREAT work!

**Comment by ottconnect** [comment]
issue has been resolved on the updated core, so issue can be closed i am able to complete the third quest without issues with a undead rogue
