### ISSUE TITLE
When my character entered the main city, worldserver.exe exited abnormally.

### ISSUE THREAD

**Issue by jiangfu204** [ottconnect/Legion#51]
When my character entered the main city, worldserver.exe exited abnormally.

------
**After the server can be set into Chinese? My English is not good**...
------

2017-06-22 01:47

This is my log address, Baidu, SkyDrive. You can download the attachment directly. My English is not very good, please forgive me

https://pan.baidu.com/s/1gfJ0quZ

This is my Crashes address

https://pan.baidu.com/s/1pLhqlo3

**Download guidelines**
![help](https://user-images.githubusercontent.com/13307848/27399315-eae84ce8-56ee-11e7-8d46-64bf08d8a9fd.png)

**Comment by ottconnect** [comment]
We are aware of the crashes when entering major cities we will address this once we get the 64bit core settled, thanks for the feedback but can you post your crash logs in the repack folder at the top. I would need the text file in the crash log.

**Comment by jiangfu204** [comment]
You can download my log. Thank you！

**Comment by ottconnect** [comment]
test core please and let me know if crash continues

https://drive.google.com/open?id=0ByMbyQDZai7zeWRVRXFrNExsMEU

**Comment by ottconnect** [comment]
issue has been resolved with the updated core, i will update ac web with the updated cores later on today

**Comment by jiangfu204** [comment]
Everything is all right, thank you
