### ISSUE TITLE
New 64 bit server bugs

### ISSUE THREAD

**Issue by Clinique2** [ottconnect/Legion#54]
Hi,

Server started up quickly with no problems. Had the following bugs after creating a Dhunter:
1. All npcs are tripled spawned on top of each other. When engaging in combat, all 3 will come.
2. Creature entry #98229 did not have quest "Assault on Mardum". When tried to lookup quest via .lookup quest Assault on Mardum, world crashed.

I have a crash log. Do I post it here? Would much rather upload if possible.  :)

**Comment by Sfrjoshpro** [comment]
Yes upload

**Comment by ottconnect** [comment]
yes we will need the crash text in the crash log at the top of the repack folder.

once you post that i will verify the crash

**Comment by ottconnect** [comment]
Legion bugs section

https://github.com/ottconnect/Legion/issues/1

**Comment by Clinique2** [comment]
Crash Logs

[5ad7e11_worldserver.exe_[21-6_19-49-15].txt](https://github.com/ottconnect/Legion/files/1095221/5ad7e11_worldserver.exe_.21-6_19-49-15.txt)
[5ad7e11_worldserver.exe_[21-6_20-14-47].txt](https://github.com/ottconnect/Legion/files/1095222/5ad7e11_worldserver.exe_.21-6_20-14-47.txt)

**Comment by ottconnect** [comment]
i will review these logs and please don't close the ticket.

**Comment by ottconnect** [comment]
download core version 1.0.1.5 to fix the server crahes

http://www.ac-web.org/forums/showthread.php?223441-Dev-Apex-Team-Legion-Repack
