### ISSUE TITLE
Как руссифицировать сервер

### ISSUE THREAD

**Issue by destroboy07** [ottconnect/Legion#55]
Всем привет! Кто подскажет как поправить полностью на русский язык игру? П.С. много квестов не переведено, в чате так же нпс говорят на эроглифах и квесты так же пишутся в чате эроглифами, сами НПС их имена на английском и эроглифы кто знает как исправить помогите
![wowscrnshot_062217_144752](https://user-images.githubusercontent.com/29624266/27424854-ac2451ce-5760-11e7-85c8-ee80dd77c707.jpg)
![wowscrnshot_062217_144842](https://user-images.githubusercontent.com/29624266/27424855-ac2c8150-5760-11e7-85f2-5b1f0cf9aa1b.jpg)
![wowscrnshot_062217_144849](https://user-images.githubusercontent.com/29624266/27424853-ac23f1e8-5760-11e7-8464-b42f0dfb9f41.jpg)
![wowscrnshot_062217_144857](https://user-images.githubusercontent.com/29624266/27424852-ac23abf2-5760-11e7-977e-c8b370dea73f.jpg)

**Comment by ottconnect** [comment]
seems like an issue with the locales tables in the database, i will have to review it once i have time.

**Comment by destroboy07** [comment]
отлично , буду ждать поправку , напишите что потом нужно сделать! чтобы исправить .

**Comment by ottconnect** [comment]
issue has been resolved for this

https://drive.google.com/file/d/0B5VMG0k0neJcVENBWmRqcHUxcnc/view

my suggestion is to use command prompt to connect to the database and import them that way so theirs no errors or warnings.

Don't use heidisql to import them or you will get an error.

**Comment by destroboy07** [comment]
Спасибо большое,только теперь скажите пожалуйста куда вставить эти файлы?

2017-06-29 3:58 GMT+07:00 Dev Apex Team <notifications@github.com>:
