### ISSUE TITLE
Application DevapexteamEmu worldserver stopped working

### ISSUE THREAD

**Issue by nixamor22** [ottconnect/Legion#56]
When i log into the game server automaticly crashes 
cant even see any npc i think that's it because server is crashing when i am logging in

**Comment by ottconnect** [comment]
whats you core platform 64bit or 32bit

**Comment by nixamor22** [comment]
it's 64 bit

**Comment by nixamor22** [comment]
i offed firewall,antivirus,tried open this with admin,etc

**Comment by ottconnect** [comment]
https://drive.google.com/open?id=0ByMbyQDZai7zeWRVRXFrNExsMEU

download this core, thats all we have been talking for the passed days

scrool down this post and it askes user to download this and test this

http://www.ac-web.org/forums/showthread.php?223441-Dev-Apex-Team-Legion-Repack&p=2275980&viewfull=1#post2275980

**Comment by nixamor22** [comment]
Okay thanks for answer 🗡

**Comment by nixamor22** [comment]
Worldserver closes after it is loaded :/ i think not it is working

**Comment by ottconnect** [comment]
I need the dberror.log and crash logs, ive tested this core 100% before i released it

**Comment by nixamor22** [comment]
[GD98KL1_worldserver.exe_[22-6_22-12-16].txt](https://github.com/ottconnect/Legion/files/1096128/GD98KL1_worldserver.exe_.22-6_22-12-16.txt)

**Comment by nixamor22** [comment]
i dont have Dberror.log or i don't get any error from this i dunno ;/

**Comment by ottconnect** [comment]
re download everything even the database and the core i just gave you, make sure you grab the dbc and maps and vmaps from my post on ac web.

**Comment by nixamor22** [comment]
gosh with my 400kb/s it will hurt me XD

**Comment by ottconnect** [comment]
its either that or i need the dberror log and if you dont have that means you don't have the Logs folder provided with the core

**Comment by nixamor22** [comment]
Okay i found a solution the Worldserver from the old Core Opened 2 times one (one was hidden but i found it and executed ) then i installed [test-core64bit.rar ] And everything is running nice, no crashes yet :)
Thanks for your help man :D u still need those logs or?

**Comment by nixamor22** [comment]
Also the port in Worldserver.conf is wrong couldn't logg then i changed it back to normal and worked :p

**Comment by ottconnect** [comment]
nope as long as it works i don't need the dberro logs

cheers

**Comment by ottconnect** [comment]
The port is always 3307 and not 3306 by default because I use 3306 for other stuff
