### ISSUE TITLE
Darkshore missing quest loot

### ISSUE THREAD

**Issue by LeRutY** [ottconnect/Legion#58]
Quest: "Buzzbox 413"

Corrupted Tide Crawler (IdTip: 32935) don´t drop quest loot (Corrupted Tide Crawler Flesh (Wow Head Id: 44863)).

**Comment by ottconnect** [comment]
i've verified that the missing loot is not added to the database, i will be adding it to the version 1.0.1.6.

Thanks for your feedback

**Comment by ottconnect** [comment]
insert this in the database editor

INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (32935, 44863, 0, 40.03, 1, 1, 0, 1, 1, NULL);

**Comment by ottconnect** [comment]
issue had been resolved for the next update

**Comment by LeRutY** [comment]
That´s great, thank you!
