### ISSUE TITLE
Innkeeper in Area 52 Only Option is make this your new home

### ISSUE THREAD

**Issue by skye22** [ottconnect/Legion#75]
Location: Rusty Rocket Tavern, Area 52

- [x] NPC: Innkeeper Remi Dodoso

**Comment by ottconnect** [comment]
issue should be resolved with flags.

**Comment by ottconnect** [comment]
https://wow.gamepedia.com/Innkeeper_Remi_Dodoso

doesn't mention vendor option to it?
wondering if they removed it

**Comment by ottconnect** [comment]
I'm not getting any confirmation so as per my research it comes to my attention that this is an innkeeper and not a vendor
