### ISSUE TITLE
Luther's Journal Not Giving Quest

### ISSUE THREAD

**Issue by skye22** [ottconnect/Legion#76]
Item dropped in Borean Tundra, but does not give the quest
 
http://www.wowhead.com/item=34719/luthers-journal

Character: Tauren Balanace Druid Level 70

**Comment by ottconnect** [comment]
Can't reproduce this issue with a Tauren Druid Level 70
I finish quest Untold Truth since its the quest before, then the questgiver gives me quest Nerub'ar Secrets and i get item Luthers Journal and return it to the quest ender

So i see no issues after playing it on the repack updated version.
