### ISSUE TITLE
Rogue Stealth

### ISSUE THREAD

**Issue by TheDrRobert** [ottconnect/Legion#92]
- [x] Say's the character is in stealth but no animation or actual effect.

**Comment by reidpr12** [comment]
Im having the same problem with rogue stealth

**Comment by buenodart** [comment]
Im having the same problem and the skill doesn't work. If i want to use a skill that requires stealth mode, this skill doesn't work.

**Comment by ottconnect** [comment]
https://github.com/ottconnect/Legion/issues/129
